name: Docker Build for Service 1

on:
  push:
    branches:
      - order-service
  pull_request:
    branches:
      - order-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for Service 1
        run: docker build . --file Dockerfile --tag service1-container:$(date +%s)
