name: Docker Image CI (Order Service)

on:
  push:
    branches:
      - orderService
  pull_request:
    branches:
      - orderService

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image for Order Service
        run: docker build ./order-service -f order-service/Dockerfile --tag order-service-container:$(date +%s)
