version: '3'

services:
  customer-service:
    image: ropsen/customer-service:latest
    ports:
      - "8081:8080"  # Map container port 8080 to host port 8081

  dashboard-service:
    image: ropsen/dashboard-service:latest
    ports:
      - "8082:8080"  # Map container port 8080 to host port 8082

  delivery-service:
    image: ropsen/delivery-service:latest
    ports:
      - "8083:8080"  # Map container port 8080 to host port 8083

  order-service:
    image: ropsen/order-service:latest
    ports:
      - "8084:8080"  # Map container port 8080 to host port 8084

  restaurant-service:
    image: ropsen/restaurant-service:latest
    ports:
      - "8085:8080"  # Map container port 8080 to host port 8085
