# Server is to be incremented by 1 for each service
server:
  port: 8084

spring:
  application:
    name: delivery

  datasource:
    url: jdbc:mysql://localhost:3306/mtogo_delivery_service
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: delivery-service-group

    producer:
      bootstrap-servers: localhost:9092

  cloud:
    stream:
      bindings:
        output:
          # Produces to these topics
          destination: test123
        input:
          # Consumes from these topics
          destination: test123
