# Server is to be incremented by 1 for each service
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mtogo_order_service
    username: root
    password: Password123!
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-group

    producer:
      bootstrap-servers: localhost:9092

  cloud:
    stream:
      bindings:
        output:
          # Produces to these topics
          destination: test123
        input:
          # Consumes from these topics
          destination: test123

