# Server is to be incremented by 1 for each service
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mtogo_order_service
    username: root
<<<<<<< HEAD
    password: 1234
=======
    password: 12345
>>>>>>> f12f921a828ec70848786e93e926222d70591b88
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-group

    producer:
      bootstrap-servers: localhost:9092

  cloud:
    stream:
      bindings:
        output:
          # Produces to these topics
          destination: my-customer-topic, another-topic
        input:
          # Consumes from these topics
          destination: my-other-topic
