# Server is to be incremented by 1 for each service
server:
  port: 8082

spring:
  application:
    name: customer

  datasource:
    url: jdbc:mysql://localhost:3306/mtogo_restaurant_service
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: restaurant-service-group

    producer:
      bootstrap-servers: localhost:9092

  cloud:
    stream:
      bindings:
        output:
          # Produces to these topics
          destination: my-restaurant-topic, another-topic
        input:
          # Consumes from these topics
          destination: my-other-topic
