name: Docker Image CI

on:
  push:
    branches:
      - main
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images for services
        run: |
          for service in customer-service dashboard-service delivery-service order-service restaurant-service; do
            echo "Building and pushing Docker image for $service"
            docker build . --file Dockerfile --tag $service:latest --build-arg SERVICE=$service -t ${{ secrets.DOCKER_USERNAME }}/$service:latest
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest | tee ${service}-push.log
          done

      - name: Pull Docker images using Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml pull

      - name: Deploy locally using Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml up -d
          docker-compose up -d
