name: Docker Image CI

on:
  push:
    branches:
      - legacy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images for services
        run: |
          cd order-service
          docker build . --file Dockerfile --tag order-service:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push order-service:latest
          
          cd ../dashboard-service
          docker build . --file Dockerfile --tag dashboard-service:latest
          docker push dashboard-service:latest
          
          # Repeat the above for other services (delivery-service, order-service, restaurant-service, user, etc.)
