name: Docker Image CI

on:
  push:
    branches:
      - legacy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the application
        run: |
          # Adjust the build command based on your project structure and build tool
          ./mvnw clean install
          
          # Assuming Maven builds the JAR file in the target directory
          cp target/*.jar /usr/src/app/my-app.jar

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
